benchmarks:
  - name: tarfind
    filename: tarfind # (optional, default value is name) 
    scale_factor: 46 
    iterations: 5
    boards:
    - board_name: native
      supported_environments:
        - name: jerryscript
          env:
            HEAP: 8 #kb
            PROFILE: es5.1

        - name: lua
          env:
            HEAP: 60000 
            GC_AGGRESSIVE: "ON"

        - name: micropython
          env:
            HEAP: 25000 # 32 * 1024

        - name: native
        - name: wamr
          env: 
            HEAP: 16384 # 16 * 1024
            STACK: 8192 # 8 * 1024

    - board_name: adafruit-feather-nrf52840-sense 
      supported_environments:
        - name: jerryscript
        - name: lua
          disabled: true # -> not enough memory
        - name: micropython
        - name: native
        - name: wamr
    - board_name: esp32-wroom-32
      supported_environments:
        - name: jerryscript
        - name: lua
        - name: micropython 
          disabled: true # -> micropython does not run on esp32 boards, they are blacklisted
        - name: native
        - name: wamr

  - name: crc_32
    filename: crc_32
    scale_factor: 170
    iterations: 5
    boards: 
    - board_name: native
      supported_environments:
        - name: jerryscript
          env:
            HEAP: 30
            PROFILE: es5.1

        - name: lua
          env:
            HEAP: 60000
        - name: micropython
          env:
            HEAP: 12000 # GC: total: 11904, used: 5312, free: 6592
        - name: native
        - name: wamr
    - board_name: adafruit-feather-nrf52840-sense 
      supported_environments:
        - name: jerryscript 
          disabled: true # -> takes way too long because of the included Int64 library
        - name: lua
        - name: micropython
        - name: native
        - name: wamr
    - board_name: esp32-wroom-32
      supported_environments:
        - name: jerryscript 
          disabled: true # -> takes way too long because of the included Int64 library
        - name: lua
        - name: micropython 
          disabled: true # -> micropython does not run on esp32 boards, they are blacklisted
        - name: native
        - name: wamr

  - name: md5
    scale_factor: 66
    iterations: 5
    boards:
    - board_name: native
      supported_environments:
        - name: jerryscript
          env:
            HEAP: 20 #kb
        - name: lua
          env:
            HEAP: 95000
        - name: micropython
          env:
            HEAP: 15000

        - name: native
        - name: wamr

    - board_name: adafruit-feather-nrf52840-sense 
      supported_environments:
        - name: jerryscript
        - name: lua
          disabled: true # -> not enough memory
        - name: micropython
        - name: native
        - name: wamr
    - board_name: esp32-wroom-32
      supported_environments:
        - name: jerryscript
        - name: lua
        - name: micropython 
          disabled: true # -> micropython does not run on esp32 boards, they are blacklisted
        - name: native
        - name: wamr

  - name: xgboost
    scale_factor: 1
    iterations: 5
    boards:
    - board_name: native
      supported_environments:
        - name: jerryscript
          env:
            HEAP: 255 #kb
            STACK: 50
            PROFILE: es5.1

        - name: lua
          env:
            HEAP: 1010000

        - name: micropython
          env:
            HEAP: 600000

        - name: native
        - name: wamr
          env: 
            HEAP: 16384
            STACK: 8192

    - board_name: adafruit-feather-nrf52840-sense 
      supported_environments:
        - name: jerryscript
        - name: lua
          disabled: true # -> not enough memory
        - name: micropython
        - name: native
        - name: wamr
    - board_name: esp32-wroom-32
      supported_environments:
        - name: jerryscript
        - name: lua
        - name: micropython 
          disabled: true # -> micropython does not run on esp32 boards, they are blacklisted
        - name: native
        - name: wamr

  - name: libud
    scale_factor: 1785
    iterations: 5
    boards:
    - board_name: native
      supported_environments:
        - name: jerryscript
          env:
            HEAP: 7 #kb
            PROFILE: es5.1
        - name: lua
          env:
            HEAP: 35000
        - name: micropython
          env:
            HEAP: 11000

        - name: native
        - name: wamr

    - board_name: adafruit-feather-nrf52840-sense 
      supported_environments:
        - name: jerryscript
        - name: lua
          disabled: true # -> not enough memory
        - name: micropython
        - name: native
        - name: wamr
    - board_name: esp32-wroom-32
      supported_environments:
        - name: jerryscript
        - name: lua
        - name: micropython 
          disabled: true # -> micropython does not run on esp32 boards, they are blacklisted
        - name: native
        - name: wamr
